name: Swift

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-26
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Clean
      run: xcodebuild clean
    - name: Build
      run: xcodebuild build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Test
      run: xcodebuild test -scheme Timer -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
